### ISSUE TITLE
Pi Zero W Support

### ISSUE THREAD

**Issue by joejoethejoey** [Anonymousdog/displaycameras#53]
Is it possible to run displaycameras on a Raspberry Pi Zero W?

Would only need it for 4 cameras maximum.

**Comment by k3bonzo** [comment]
Hi joejoethejoey, 
Yes, you can display 4 cameras using Raspberry Pi Zero W. 

I have tested Raspberry Pi Zero W and able to display 8 (low resolution)  RTSP cameras  on 1920x1080 on 3x3 display matrix.

in you plan  to only for 4 cameras, check this video

**Comment by joejoethejoey** [comment]
Great!  Thanks k3bonzo!!

**Comment by joejoethejoey** [comment]
> Hi joejoethejoey,
> Yes, you can display 4 cameras using Raspberry Pi Zero W.
> 
> I have tested Raspberry Pi Zero W and able to display 8 (low resolution) RTSP cameras on 1920x1080 HDMI TV - using 3x3 display matrix.

Hi k3bonzo,

I've been trying to add extra cameras to the display.  For some reason, no matter if I use 2x2 screen on 2 matrix or a 3x3, it will only display 6 cameras max.  I'm using low resolution RTSP (640x360).  I've checked all the code and it all looks correct to me:

`# Window names

# 3x3 screen with 1 off-screen windows
windows=(upper_left upper_middle upper_right center_left center_middle center_right lower_left lower_middle lower_right off_screen)
# Make sure to account for each window above in the list below.

# Windows positions

window_positions=(
#First Row
#upper_left
# 640x360
"0 0 639 359" \
#upper_middle
"640 0 1279 359" \
#upper_right
"1280 0 1920 359" \

#Second Row (missing all but the far right window because large_left is double size
#center_left
# 640x360
"0 360 639 719" \
#center_middle
"640 360 1279 719" \
#center_right
"1280 360 1920 719" \

#Third Row
#lower_left
# 640x360
"0 720 639 1079" \
#lower_middle
"640 720 1279 1079" \
#lower_right
"1280 720 1919 1079" \
)

# Camera Names
camera_names=(cam1 cam2 cam3 cam4 cam5 cam6 cam7 cam8 cam9)
# Make sure to account for each camera above in the list of feeds below.

# Camera Feeds

camera_feeds=( \
# Low-Res
#cam1
"rtsp://192.168.1.XXX:XXX/5cdd5849d36e93XXXa5e71d_2" \
#cam2
"rtsp://192.168.1.XXX:XXX/5cdd5849d36e93XXXa5e71d_2" \
#cam3
"rtsp://192.168.1.XXX:XXX/5cdd5849d36e93XXXa5e71d_2" \
#cam4
"rtsp://192.168.1.XXX:XXX/5cdd5849d36e93XXXa5e71d_2" \
#cam5
"rtsp://192.168.1.XXX:XXX/5cdd5849d36e93XXXa5e71d_2" \
#cam6
"rtsp://192.168.1.XXX:XXX/5cdd5849d36e93XXXa5e71d_2" \
#cam7
"rtsp://192.168.1.XXX:XXX/5cdd5849d36e93XXXa5e71d_2" \
#cam8
"rtsp://192.168.1.XXX:XXX/5cdd5849d36e93XXXa5e71d_2" \
#cam9
"rtsp://192.168.1.XXX:XXX/5cdd5849d36e93XXXa5e71d_2" \
)

# Are we rotating cameras through the window matrix? (default false if not set here)
#rotate="true"`

**Comment by k3bonzo** [comment]
> Hi joejoethejoey,

Your layout  declare 1 off-screen in 'windows=(........ off_screen), but you not define off_screen position point in  'windows_position ( ...........   ). After  # Third Row ...... ...' 

I use 3x3 screen with 3 off_screen position, find below layout  for 8 cameras that works for me:  
-- don't forget to remove apostrophe (') in front of #  .
 
'# This is the camera feed/windows layout configuration file for the displaycameras service.  It ONLY configures the layout and 
'# feeds for the cameras; the rest of the configuration is in displaycameras.conf. See the comments in that file for notes on 
'# configuring the below.

'# Window names

'# 3x3 screen with 3 off-screen windows
windows=(upper_left upper_middle upper_right center_left center_middle center_right lower_left lower_middle lower_right off_screen off_screen1 off_screen2)
'# Make sure to account for each window above in the list below.

'# Windows positions

window_positions=(
'#First Row
'#upper_left
"0 0 639 359" \
'#upper_middle
"640 0 1279 359" \
'#upper_right
"1280 0 1919 359" \

'#Second Row (missing all but the far right window because large_left is double size
'#center_left
"0 360 639 719" \
'#center_middle
"640 360 1279 719" \
'#center_right
"1280 360 1919 719" \

'#Third Row
'#lower_left
"0 720 639 1079" \
'#lower_middle
"640 720 1279 1079" \
'#lower_right
"1280 720 1919 1079" \

'#off-screen
"1920 0 3839 1079" \
"1920 1080 3839 2159" \
"0 1080 1919 2159" \
)

'# Camera Names
camera_names=(cam1 cam2 cam3 cam4 cam5 cam6 cam7 cam8 cam9)
'# Make sure to account for each camera above in the list of feeds below.

'# Camera Feeds

camera_feeds=( \
'# Low-Res
'#cam1
"rtsp://192.168.1.xxx:xxx/streaming/camera/01" \
'#cam2
"rtsp://192.168.1.xxx:xxx/streaming/camera/02" \
'#cam3
"rtsp://192.168.1.xxx:xxx/streaming/camera/03" \
'#cam4
"rtsp://192.168.1.xxx:xxx/streaming/camera/04" \
'#cam5
"rtsp://192.168.1.xxx:xxx/streaming/camera/05" \
'#cam6
"rtsp://192.168.1.xxx:xxx/streaming/camera/06" \
'#cam7
"rtsp://192.168.1.xxx:xxx/streaming/camera/07" \
'#cam8
"rtsp://192.168.1.xxx:xxx/streaming/camera/08" \
'#cam9
'# keep it no camera feed/ stream for this one
"<Camera stream URL>" \
)

'# Are we rotating cameras through the window matrix? (default false if not set here)
rotate="false"

**Comment by joejoethejoey** [comment]
Thanks k3bonzo for your reply.  My bad, I forgot to edit the off_screen cam off the code posted previously.  My actual code doesn't have that.  Either way though, it still only displays 6 cameras.  I've also tried the layout you linked.  The third row doesn't show anything.  Any other ideas?

Thanks again!

**Comment by joejoethejoey** [comment]
I've been using the code for a few days now.  I've noticed that it still only displays 6 cameras, but it randomly chooses to display a different set of 6 cameras.  Originally it was only cameras 1-6.  For the last 2 days, it's been cameras 2, 3, 5, 6, 8 and 9.  Could it be a  ram issue in the Pi Zero?

**Comment by k3bonzo** [comment]
Memory split setting on my raspi Zero W is  256MB

**Comment by joejoethejoey** [comment]
I have set the same.  Is it worthwhile increasing to max 512MB?  Is there a way to increase incrementally to test rather than start afresh?

Thanks!

**Comment by Anonymousdog** [comment]
> I have set the same. Is it worthwhile increasing to max 512MB? Is there a way to increase incrementally to test rather than start afresh?
> 
> Thanks!

Yes, with rpi-config.
